# 使用pickle序列化numpy array

In [25]:
import pickle
import numpy as np

In [26]:
x = np.arange(10)

In [27]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
f = open('x.pkl', 'wb')

In [29]:
pickle.dump(x, f)

In [30]:
!ls

Array.ipynb		    one_array.npy  x.pkl
Array的input与output.ipynb  two_array.npz  快速创建数组.ipynb


In [33]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
f = open('x.pkl', 'rb')

In [35]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.save('one_array', x)

In [37]:
!ls

Array.ipynb		    one_array.npy  x.pkl
Array的input与output.ipynb  two_array.npz  快速创建数组.ipynb


In [38]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
y = np.arange(20)

In [40]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
np.savez('two_array.npz', a=x, b=y)

In [42]:
!ls

Array.ipynb		    one_array.npy  x.pkl
Array的input与output.ipynb  two_array.npz  快速创建数组.ipynb


In [44]:
c = np.load('two_array.npz')

In [45]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])