In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# Concatenate

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
arr2 = np.arange(9).reshape(3,3)

In [5]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1,arr2],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [7]:
s1 = Series([1,2,3], index=['X','Y','Z'])

In [8]:
s2 = Series([4,5], index=['A','B'])

In [9]:
s1

X    1
Y    2
Z    3
dtype: int64

In [10]:
s2

A    4
B    5
dtype: int64

In [11]:
pd.concat([s1,s2])

X    1
Y    2
Z    3
A    4
B    5
dtype: int64

In [12]:
df1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

In [13]:
df1

X         Y         Z
0  0.427892  0.609318  0.447782
1  1.617475 -0.259070  0.620019
2 -0.831285  0.780827  0.829415
3  1.305855  1.637263  0.484314

In [14]:
df2 = DataFrame(np.random.randn(3,3), columns=['X','Y','A'])

In [15]:
df2

X         Y         A
0  0.565484 -0.568502  0.074661
1  0.594557  0.186149  0.985498
2 -0.709379  0.210792  1.160285

In [16]:
pd.concat([df1,df2])

A         X         Y         Z
0       NaN  0.427892  0.609318  0.447782
1       NaN  1.617475 -0.259070  0.620019
2       NaN -0.831285  0.780827  0.829415
3       NaN  1.305855  1.637263  0.484314
0  0.074661  0.565484 -0.568502       NaN
1  0.985498  0.594557  0.186149       NaN
2  1.160285 -0.709379  0.210792       NaN

In [17]:
#For more info in documentation:
url='http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'

# Combine

In [18]:
s1 = Series([2, np.nan, 4, np.nan], index=['A','B','C','D'])

In [19]:
s1

A    2.0
B    NaN
C    4.0
D    NaN
dtype: float64

In [20]:
s2 = Series([1,2,3,4], index=['A','B','C','D'])

In [21]:
s2

A    1
B    2
C    3
D    4
dtype: int64

In [23]:
s1.combine_first(s2)

A    2.0
B    2.0
C    4.0
D    4.0
dtype: float64

In [24]:
df1 = DataFrame({
    'X': [1, np.nan, 3, np.nan],
    'Y': [5, np.nan, 7, np.nan],
    'Z': [9, np.nan, 11,np.nan]
})

In [25]:
df1

X    Y     Z
0  1.0  5.0   9.0
1  NaN  NaN   NaN
2  3.0  7.0  11.0
3  NaN  NaN   NaN

In [26]:
df2 = DataFrame({
    'Z':[np.nan, 10, np.nan, 12],
    'A':[1,2,3,4]
})

In [27]:
df2

A     Z
0  1   NaN
1  2  10.0
2  3   NaN
3  4  12.0

In [28]:
df1.combine_first(df2)

A    X    Y     Z
0  1.0  1.0  5.0   9.0
1  2.0  NaN  NaN  10.0
2  3.0  3.0  7.0  11.0
3  4.0  NaN  NaN  12.0

In [29]:
df3 = DataFrame(
{
     'X': [1,2,3],
    'Y': [5,7,9],
    'G':[6, 7, 10]
})

In [30]:
df1.fillna(df3)

X    Y     Z
0  1.0  5.0   9.0
1  2.0  7.0   NaN
2  3.0  7.0  11.0
3  NaN  NaN   NaN